ChobieGit2RepositoryBrowserBundle:
    resource: "@ChobieGit2RepositoryBrowserBundle/Resources/config/routing.php"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
